#### ***Pratyush Kumar***
##### *N052*
##### *MBA Tech CE (div. D)*

## EXPERIMENT 8 - Task 1

Building a three-layer feed forward neural network from scratch by initializing random weights and biases.

In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
import numpy as np

In [2]:
df= pd.read_csv("iris.csv")

In [3]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [5]:
df.shape

(150, 5)

In [6]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [7]:
numeric_columns = df.select_dtypes(exclude=["object"]).columns
categorical_columns = df.select_dtypes(include=["object"]).columns

In [8]:
scaler = StandardScaler()

df[numeric_columns] = scaler.fit_transform(df[numeric_columns])

In [9]:
df = pd.get_dummies(df, columns=categorical_columns, dtype=int)

In [10]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species_setosa', 'species_versicolor', 'species_virginica'],
      dtype='object')

In [11]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  species_setosa  \
0     -0.900681     1.032057     -1.341272    -1.312977               1   
1     -1.143017    -0.124958     -1.341272    -1.312977               1   
2     -1.385353     0.337848     -1.398138    -1.312977               1   
3     -1.506521     0.106445     -1.284407    -1.312977               1   
4     -1.021849     1.263460     -1.341272    -1.312977               1   

   species_versicolor  species_virginica  
0                   0                  0  
1                   0                  0  
2                   0                  0  
3                   0                  0  
4                   0                  0

In [12]:
df.describe().round(2)

sepal_length  sepal_width  petal_length  petal_width  species_setosa  \
count        150.00       150.00        150.00       150.00          150.00   
mean          -0.00        -0.00          0.00        -0.00            0.33   
std            1.00         1.00          1.00         1.00            0.47   
min           -1.87        -2.44         -1.57        -1.44            0.00   
25%           -0.90        -0.59         -1.23        -1.18            0.00   
50%           -0.05        -0.12          0.34         0.13            0.00   
75%            0.67         0.57          0.76         0.79            1.00   
max            2.49         3.11          1.79         1.71            1.00   

       species_versicolor  species_virginica  
count              150.00             150.00  
mean                 0.33               0.33  
std                  0.47               0.47  
min                  0.00               0.00  
25%                  0.00               0.00  
50%                  0.00               0.00  
75%                  1.00               1.00  
max                  1.00               1.00

In [13]:
input = df.iloc[:, 0:4]

In [14]:
input.shape

(150, 4)

In [15]:
input

sepal_length  sepal_width  petal_length  petal_width
0       -0.900681     1.032057     -1.341272    -1.312977
1       -1.143017    -0.124958     -1.341272    -1.312977
2       -1.385353     0.337848     -1.398138    -1.312977
3       -1.506521     0.106445     -1.284407    -1.312977
4       -1.021849     1.263460     -1.341272    -1.312977
..            ...          ...           ...          ...
145      1.038005    -0.124958      0.819624     1.447956
146      0.553333    -1.281972      0.705893     0.922064
147      0.795669    -0.124958      0.819624     1.053537
148      0.432165     0.800654      0.933356     1.447956
149      0.068662    -0.124958      0.762759     0.790591

[150 rows x 4 columns]

In [16]:
np.random.seed(42)

w_i_h1 = np.random.rand(4,1)
w_i_h2 = np.random.rand(4,1)

w_h_o1 = np.random.rand(2,1)
w_h_o2 = np.random.rand(2,1)
w_h_o3 = np.random.rand(2,1)

bias1 = np.random.rand(1)
bias2 = np.random.rand(1)

In [17]:
print(w_i_h1, '\n')
print(w_i_h2, '\n')
print('\n')
print(w_h_o1, '\n')
print(w_h_o2, '\n')
print(w_h_o3, '\n')
print('\n')
print(bias1, '\n')
print(bias2, '\n')

[[0.37454012]
 [0.95071431]
 [0.73199394]
 [0.59865848]] 

[[0.15601864]
 [0.15599452]
 [0.05808361]
 [0.86617615]] 



[[0.60111501]
 [0.70807258]] 

[[0.02058449]
 [0.96990985]] 

[[0.83244264]
 [0.21233911]] 



[0.18182497] 

[0.18340451] 



In [18]:
h1_in = np.dot(input, w_i_h1) + bias1
h2_in = np.dot(input, w_i_h2) + bias2

In [19]:
print(h1_in.shape)
print(h2_in.shape)

(150, 1)
(150, 1)


In [20]:
def sigmoid(x):
  return 1/(1 + np.exp(-x))

In [21]:
h1_out = sigmoid(h1_in)
h2_out = sigmoid(h2_in)

In [22]:
print(h1_out.shape)
print(h2_out.shape)

(150, 1)
(150, 1)


In [23]:
h_out = np.append(h1_out, h2_out, axis=1)
h_out.shape

(150, 2)

In [24]:
o1_in = np.dot(h_out, w_h_o1)
o2_in = np.dot(h_out, w_h_o2)
o3_in = np.dot(h_out, w_h_o3)

In [25]:
o1 = sigmoid(o1_in)
o2 = sigmoid(o2_in)
o3 = sigmoid(o3_in)

In [26]:
print(o1.shape)
print(o2.shape)
print(o3.shape)

(150, 1)
(150, 1)
(150, 1)
